name: flutter_testing_megapack
description: "A collection of Flutter experiments"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.0.0
  equatable: ^2.0.3
  uuid: ^4.3.3

  mysql1: ^0.20.0
  pointycastle: ^3.1.1

  cupertino_icons: ^1.0.2
  dynamic_color: ^1.6.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true